FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test

WORKDIR /app

COPY . .

RUN dotnet restore
RUN dotnet build --no-restore

ENTRYPOINT ["dotnet", "test", "--no-build", "--logger:trx", "--results-directory", "/app/TestResults"]
